### ISSUE TITLE
Review HW-6 DOM.2

### ISSUE THREAD

**Issue by BUI-studies** [AKot1988/Bui-Homeworks#6]
## 1) `renderList`
`рядок 3` - значення за замовчуванням має бути масивом, а не обʼєктом. заміни на `[]` пустий масив і будь щасливий))

`рядок 4` - наче не потрібно там аперкейсом назву тега, по-моєму має маленькими літерами проканати. ба більше - ти міг в розмітці дати цьому списку `id` і знаходити його за `id`.

з приводу послідовності рендеру елементів. спочатку вкладай в лішку те шо там маж бути і тіки потім пхай її на сторінку. у тебе ж зараз воно трохи сумбурно. при повільному інтернеті або компухтері користувач буде бачити наче глітч коли все ото поступово і заотично зʼявляється на екрані.

___

## 2) `clearLinksPage`
замість `getAttribute` можна було просто стукатись до властивості `href`.

___

## 3) `filterClothes`
не вважаю коректним змінну з повідомленням про помилку називати `newInformation`. краще обізвати `errorEl` або `errorItem`, або якось іще аби тіки було зрозуміло що це саме помилка.

> не забувай вичищати консолі перед здачею!!!

усе інше просто канфекта!!

**Comment by AKot1988** [comment]
+
